### ISSUE TITLE
new igraph issue

### ISSUE THREAD

**Issue by schochastics** [zpneal/incidentally#3]
see: https://github.com/igraph/rigraph/pull/633#issuecomment-1384205381

I think this is independent from the new igraph version. I get an error here: https://github.com/zpneal/incidentally/blob/release/vignettes/congress.Rmd#L95

This is what B looks like for me when I run the vignette line by line
```
R> B
IGRAPH 4a10b64 UN-B 451 7909 -- 
+ attr: name (v/c), type (v/l), party (v/c), state (v/c), last (v/c), id (v/c),
| introduced (v/c), title (v/c), area (v/c), status (v/c)
+ edges from 4a10b64 (vertex names):
 [1] Sen. Cardin, Benjamin L. [D-MD]    --NANA   
 [2] Sen. McCain, John [R-AZ]           --NANA   
 [3] Sen. Markey, Edward J. [D-MA]      --NANA   
 [4] Sen. Coons, Christopher A. [D-DE]  --NANA   
 [5] Sen. Schatz, Brian [D-HI]          --NANA   
 [6] Sen. Feinstein, Dianne [D-CA]      --NANA   
 [7] Sen. Hirono, Mazie K. [D-HI]       --NANA   
+ ... omitted several edges
```

This is the error message at the end:
```
Quitting from lines 114-116 (congress.Rmd) 
   Error: processing vignette 'congress.Rmd' failed with diagnostics:
   'x' must be an array of at least two dimensions
   --- failed re-building ‘congress.Rmd’
   
   --- re-building ‘incidentally.Rmd’ using rmarkdown
   --- finished re-building ‘incidentally.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘congress.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
```

**Comment by zpneal** [comment]
I think you're right this is unrelated to igraph. I was aware of this issue, and it should be fixed in the development version available via `devtools::install_github("zpneal/incidentally", ref = "devel")`. I've been waiting to update CRAN for a couple other changes I'm working on.

**Comment by schochastics** [comment]
hmm I am not sure that it is fixed. I cloned the repository so that should contain "the fix" but I get the error. Maybe some data that gets downloaded is not there anymore? thats at least what i get the impression.

**Comment by zpneal** [comment]
Hmm, when you cloned the repo, did you notice there are two branches: `release` and `devel`? I get the error in `release`, but not in `devel` where I made the fix. It's related to the fact that US Congress is in the process of updating the XML tags used in their bulk data.

**Comment by schochastics** [comment]
ah I see. I got release, so that explains it. I dont get the error when switching to devel, so that should be fixed then :+1:

**Comment by zpneal** [comment]
Whew! Thanks for checking.
